baseURL = "https://portfolio-web.vercel.app/"
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = false
enableGitInfo = false
enableRobotsTXT = true

# Tema Hextra via Hugo Modules
[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false

[build]
  [build.buildStats]
    enable = true
