[[main]]
  name = "Projects"
  pageRef = "/#projetos"
  weight = 1

[[main]]
  name = "Contact"
  pageRef = "/#contato"
  weight = 2

[[main]]
  name = "GitHub"
  url = "https://github.com/MathBriton"
  weight = 3
  [main.params]
    icon = "github"
